import { test, expect } from '@playwright/test';

async function login(page){
  await page.goto('/');await page.getByLabel('Adgangsnøgle',{exact:true}).fill('browser-test-access-key-123456789');
  await page.getByRole('button',{name:'Forbind til Codex'}).click();
  await expect(page.locator('#connection-label')).toHaveText('Forbundet');
  await page.getByRole('button',{name:/Byg et browser-UI/}).click();
  await expect(page.locator('#session-status')).toHaveText('Klar');
}
test('desktop: history, safe rendering, streaming, approvals, questions, steering, stop, reload and logout',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await login(page);
  await expect(page.locator('#messages')).toContainText('lokale Codex-server');
  expect(await page.evaluate(()=>window.compromised)).toBeUndefined();
  await expect(page.locator('#messages a[href^="javascript:"]')).toHaveCount(0);
  await page.getByText('pwd',{exact:false}).first().click();
  await expect(page.locator('details[open]')).toHaveCount(1);
  await page.locator('#message').fill('test streaming');await page.getByRole('button',{name:'Send besked',exact:true}).click();
  await expect(page.locator('#messages')).toContainText('Svaret streames fra din maskine.');
  await expect(page.locator('#session-status')).toHaveText('Klar');
  await page.locator('#message').fill('approval');await page.getByRole('button',{name:'Send besked',exact:true}).click();
  await expect(page.getByText('Din godkendelse er nødvendig')).toBeVisible();
  await page.getByRole('button',{name:'Godkend én gang'}).click();
  await expect(page.locator('#requests')).toBeEmpty();
  await page.locator('#message').fill('question');await page.getByRole('button',{name:'Send besked',exact:true}).click();
  await page.getByLabel('Hvilken farve?',{exact:true}).fill('Grøn');await page.getByRole('button',{name:'Send svar',exact:true}).click();
  await expect(page.locator('#requests')).toBeEmpty();
  await page.locator('#message').fill('long');await page.getByRole('button',{name:'Send besked',exact:true}).click();
  await expect(page.locator('#interrupt')).toBeVisible();
  await page.locator('#message').fill('Fokusér på tests');await page.locator('#steer').click();
  await expect(page.locator('#messages')).toContainText('Fokusér på tests');
  await page.locator('#interrupt').click();await expect(page.locator('#messages')).toContainText('Stoppet');
  await page.locator('#message').fill('Min kladde');await page.getByRole('button',{name:/Mit andet projekt/}).click();
  await expect(page.locator('#message')).toHaveValue('');await page.getByRole('button',{name:/Byg et browser-UI/}).click();
  await expect(page.locator('#message')).toHaveValue('Min kladde');
  await page.reload();await expect(page.locator('#session-title')).toHaveText('Byg et browser-UI');
  await expect(page.locator('#messages')).toContainText('Fokusér på tests');
  await page.screenshot({path:'test-results/desktop.png',fullPage:true,animations:'disabled'});
  expect(errors).toEqual([]);
  await page.getByRole('button',{name:'Log ud',exact:true}).click();await expect(page.locator('#login')).toBeVisible();
});
test('mobile: navigation, no overflow, search and new project session',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');await page.getByLabel('Adgangsnøgle',{exact:true}).fill('browser-test-access-key-123456789');await page.getByRole('button',{name:'Forbind til Codex'}).click();
  await expect(page.locator('#connection-label')).toHaveText('Forbundet');
  await page.getByRole('button',{name:'Vis sessions',exact:true}).click();
  await page.getByLabel('Søg i sessions').fill('browser');
  await expect(page.locator('.session-row')).toHaveCount(1);
  await page.getByRole('button',{name:/Byg et browser-UI/}).click();
  await expect(page.locator('#sidebar')).not.toHaveClass(/open/);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/mobile.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Vis sessions',exact:true}).click();await page.getByRole('button',{name:'Ny session',exact:false}).click();
  const newPath=(await page.locator('#cwd').inputValue())+'/new-project';
  await page.getByLabel('Projektmappe',{exact:true}).fill(newPath);await expect(page.locator('#project-status')).toContainText('Mappen findes ikke');await page.locator('#create-directory').check();await page.getByRole('button',{name:'Opret mappe og session'}).click();
  await expect(page.locator('#session-path')).toHaveText(newPath);
});
test('preferences, translated drafts, changes tabs and queue edit/cancel/steer/recall',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await login(page);
  await page.locator('#message').fill('long');await page.locator('#send').click();await expect(page.locator('#interrupt')).toBeVisible();
  await page.locator('#message').fill('Queue original');await page.locator('#send').click();
  await expect(page.locator('#queue-list')).toContainText('Queue original');
  await page.reload();await expect(page.locator('#queue-list')).toContainText('Queue original');
  await page.locator('#message').press('ArrowUp');await expect(page.locator('#message')).toHaveValue('Queue original');
  await expect(page.locator('#edit-mode')).toContainText('Redigerer');await expect(page.locator('#queue-list')).toBeEmpty();
  await page.locator('#message').fill('Queue edited');await page.locator('#send').click();
  await expect(page.locator('#queue-list')).toContainText('Queue edited');
  await page.getByRole('button',{name:'Send som steer',exact:true}).click();
  await expect(page.locator('#messages')).toContainText('Queue edited');await expect(page.locator('#queue-list')).toBeEmpty();
  await page.locator('#message').press('ArrowUp');await expect(page.locator('#message')).toHaveValue('Queue edited');await expect(page.locator('#edit-mode')).toBeHidden();
  await page.locator('#message').fill('cancel me');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('cancel me');
  await page.getByRole('button',{name:'Annullér besked',exact:true}).click();await expect(page.locator('#queue-list')).toBeEmpty();
  await page.locator('#interrupt').click();await expect(page.locator('#session-status')).toHaveText('Klar');
  await page.locator('#message').fill('Min urørte kladde');
  await page.locator('#workspace [data-language-select]').selectOption('en');
  await expect(page.locator('#message')).toHaveValue('Min urørte kladde');await expect(page.locator('#connection-label')).toHaveText('Connected');await expect(page.locator('#toggle-changes')).toHaveText('Changed files');
  await page.locator('#workspace [data-theme-toggle]').click();
  const theme=await page.locator('html').getAttribute('data-theme');
  await page.locator('#codex-tab').click();await expect(page.locator('#changed-files')).toContainText('app.js');
  await page.locator('.changed-file').click();await expect(page.locator('#change-detail')).toContainText('<script>unsafe</script>');
  await page.screenshot({path:`test-results/changes-${theme}.png`,fullPage:true});
  await page.locator('#git-tab').press('Home');await expect(page.locator('#codex-tab')).toBeFocused();
  await page.locator('#git-tab').click();await expect(page.locator('#changed-files')).toContainText('untracked.txt');await page.locator('.changed-file').click();await expect(page.locator('#change-detail')).toContainText('<script>only text</script>');
  await page.locator('#workspace [data-theme-toggle]').click();await page.screenshot({path:'test-results/changes-other-theme.png',fullPage:true});
  const savedTheme=await page.locator('html').getAttribute('data-theme');
  await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('html')).toHaveAttribute('data-theme',savedTheme);
  await expect(page.locator('#connection-label')).toHaveText('Connected');
  expect(await page.locator('#connection .status-dot').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(savedTheme==='light'?'rgb(22, 132, 71)':'rgb(54, 207, 125)');
  await page.locator('#message').fill('question');await page.locator('#send').click();await page.getByLabel('Hvilken farve?',{exact:true}).fill('Blå');await page.locator('#workspace [data-language-select]').selectOption('da');await expect(page.getByLabel('Hvilken farve?',{exact:true})).toHaveValue('Blå');await page.getByRole('button',{name:'Send svar',exact:true}).click();
  expect(errors).toEqual([]);
});
test('system theme and preferences work without browser storage; mobile panel closes with Escape',async({page})=>{
  await page.emulateMedia({colorScheme:'dark'});
  await page.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked');}});});
  await page.setViewportSize({width:320,height:800});
  await page.goto('/');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await page.locator('#login [data-language-select]').selectOption('en');await page.locator('#login [data-theme-toggle]').click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await page.getByLabel('Access key',{exact:true}).fill('wrong');await page.getByRole('button',{name:'Connect to Codex'}).click();await expect(page.locator('#login-error')).not.toBeEmpty();
  const englishError=await page.locator('#login-error').textContent();await page.locator('#login [data-language-select]').selectOption('da');await expect(page.locator('#login-error')).not.toHaveText(englishError);
  await page.getByLabel('Adgangsnøgle',{exact:true}).fill('browser-test-access-key-123456789');await page.getByRole('button',{name:'Forbind til Codex'}).click();
  await page.locator('#toggle-sidebar').click();await page.getByRole('button',{name:/Byg et browser-UI/}).click();await expect(page.locator('#session-status')).toHaveText('Klar');await page.locator('#toggle-changes').click();await expect(page.locator('#changes-panel')).toBeVisible();await page.locator('#close-changes').press('Escape');await expect(page.locator('#changes-panel')).toBeHidden();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/mobile-light.png',fullPage:true});
});
test('queue consumption races do not resend; failed steer preserves text and disconnect turns red',async({page})=>{
  await login(page);
  await page.locator('#message').fill('approval');await page.locator('#send').click();await expect(page.locator('#requests')).not.toBeEmpty();
  await page.locator('#message').fill('automatic next turn');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('automatic next turn');
  await page.getByRole('button',{name:'Godkend én gang'}).click();await expect(page.locator('#messages')).toContainText('automatic next turn');await expect(page.locator('#queue-list')).toBeEmpty();await expect(page.locator('#session-status')).toHaveText('Klar');
  await page.locator('#message').fill('long');await page.locator('#send').click();await expect(page.locator('#interrupt')).toBeVisible();
  await page.locator('#message').fill('already consumed');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('already consumed');
  let sends=0;page.on('request',req=>{if(req.url().endsWith('/message'))sends++;});
  await page.route('**/queue/*/delete',async route=>{await route.fetch();await route.fulfill({json:{deleted:false}});});
  await page.getByRole('button',{name:'Send som steer',exact:true}).click();await expect(page.locator('#queue-list')).toBeEmpty();expect(sends).toBe(0);await page.unroute('**/queue/*/delete');
  await page.locator('#message').fill('preserve after failure');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('preserve after failure');
  await page.route('**/message',route=>route.fulfill({status:503,json:{error:'Test delivery failure'}}));
  await page.getByRole('button',{name:'Send som steer',exact:true}).click();await expect(page.locator('#queue-list')).toContainText('Afsendelsen blev ikke bekræftet');await expect(page.locator('#queue-list')).toContainText('preserve after failure');
  await page.getByRole('button',{name:'Gendan besked i skrivefeltet',exact:true}).click();await expect(page.locator('#message')).toHaveValue('preserve after failure');await page.unroute('**/message');
  await page.locator('#message').fill('lost delete acknowledgement');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('lost delete acknowledgement');
  await page.route('**/queue/*/delete',async route=>{await route.fetch();await route.abort('failed');});
  await page.getByRole('button',{name:'Tag ud af kø og redigér',exact:true}).click();await expect(page.locator('#queue-list')).toContainText('Afsendelsen blev ikke bekræftet');await page.unroute('**/queue/*/delete');
  await page.getByRole('button',{name:'Gendan besked i skrivefeltet',exact:true}).click();await expect(page.locator('#message')).toHaveValue('lost delete acknowledgement');
  await page.locator('#interrupt').click();
  await page.route('**/api/events',route=>route.fulfill({contentType:'text/event-stream',body:'event: status\ndata: {"state":"disconnected"}\n\n'}));await page.reload();await expect(page.locator('#connection-label')).toHaveText('Forbindelse afbrudt');
  const theme=await page.locator('html').getAttribute('data-theme');expect(await page.locator('#connection .status-dot').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(theme==='light'?'rgb(205, 52, 52)':'rgb(242, 105, 105)');
});
test('processing ends editing on live turn start and message receipt without losing the next draft',async({page})=>{
  await login(page);
  await page.locator('#message').fill('long');await page.locator('#send').click();await expect(page.locator('#interrupt')).toBeVisible();
  await page.locator('#message').fill('withdraw this');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('withdraw this');
  await page.locator('#message').press('ArrowUp');await expect(page.locator('#edit-mode')).toBeVisible();await page.locator('#message').fill('my next draft');
  await page.locator('#interrupt').click();await expect(page.locator('#session-status')).toHaveText('Klar');
  // Another client starts work while this browser has an edit open.
  await page.request.post('/api/threads/session-one/message',{data:{text:'long'}});
  await expect(page.locator('#edit-mode')).toBeHidden();await expect(page.locator('#message')).toHaveValue('my next draft');
  await expect(page.locator('#composer-status')).toContainText('Codex arbejder');
  await page.locator('#timeline').evaluate(el=>{el.scrollTop=0;});await expect(page.locator('#composer-status')).toBeInViewport();
  await expect(page.locator('#send')).toHaveAttribute('aria-label','Sæt besked i kø');
  await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('my next draft');
  await page.locator('#message').press('ArrowUp');await expect(page.locator('#edit-mode')).toBeVisible();await page.locator('#message').fill('steer with delayed acknowledgement');
  let release;const gate=new Promise(resolve=>{release=resolve;});
  await page.route('**/message',async route=>{const response=await route.fetch();await gate;await route.fulfill({response});});
  try {
    await page.locator('#steer').click();
    await expect(page.locator('#messages')).toContainText('steer with delayed acknowledgement');
    await expect(page.locator('#edit-mode')).toBeHidden();await expect(page.locator('#queue-list')).not.toContainText('Sender…');
    await page.locator('#message').fill('new text while the response is pending');
  } finally {release();}
  await expect(page.locator('#send')).toBeEnabled();await expect(page.locator('#message')).toHaveValue('new text while the response is pending');
  await page.unroute('**/message');await page.locator('#interrupt').click();await expect(page.locator('#composer-status')).toBeHidden();
  await page.locator('#message').fill('');await page.locator('#message').press('ArrowUp');await expect(page.locator('#edit-mode')).toBeHidden();await expect(page.locator('#message')).toHaveValue('steer with delayed acknowledgement');
});
test('active snapshot shows processing and queues new messages before turn details arrive',async({page})=>{
  await login(page);
  await page.route('**/session-one/open',async route=>{const response=await route.fetch();const body=await response.json();body.thread.status={type:'active',activeFlags:[]};await route.fulfill({response,json:body});});
  await page.reload();
  await expect(page.locator('#composer-status')).toContainText('Codex arbejder');await expect(page.locator('#session-status')).toHaveText('Arbejder');
  await page.locator('#message').fill('next task before turn details');await expect(page.locator('#send')).toHaveAttribute('aria-label','Sæt besked i kø');await expect(page.locator('#steer')).toBeDisabled();
  await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('next task before turn details');
  await page.getByRole('button',{name:'Annullér besked',exact:true}).click();await expect(page.locator('#queue-list')).toBeEmpty();
});

test('new session suggests folders with keyboard selection and validates missing paths',async({page})=>{
  await login(page);const root=await page.locator('#session-path').textContent();
  await page.locator('#new-session').click();await page.locator('#cwd').fill(root+'/new-');
  await expect(page.locator('#project-suggestions')).toContainText(root+'/new-project');
  await page.locator('#cwd').press('ArrowDown');await page.locator('#cwd').press('Enter');await expect(page.locator('#cwd')).toHaveValue(root+'/new-project');await expect(page.locator('#create-session')).toBeEnabled();
  await page.locator('#cwd').fill(root+'/untracked.txt');await expect(page.locator('#project-status')).toContainText('Stien peger på en fil');await expect(page.locator('#create-session')).toBeDisabled();
  await page.locator('#cwd').fill(root+'/brand new project');await expect(page.locator('#project-status')).toContainText('Mappen findes ikke');await expect(page.locator('#create-session')).toBeDisabled();
  await page.locator('#create-directory').check();await expect(page.locator('#create-session')).toHaveText(/Opret mappe og session/);
  await page.evaluate(()=>window.remoteCodexPreferences.set('language','en'));await expect(page.locator('#create-session')).toHaveText(/Create folder and session/);await expect(page.locator('#cwd')).toHaveValue(root+'/brand new project');
  await page.locator('#cwd').fill(root);await expect(page.locator('#project-status')).toContainText('The folder exists');await expect(page.locator('#create-directory')).not.toBeChecked();await expect(page.locator('#create-session')).toHaveText(/Create session/);
  await page.locator('#close-dialog').click();
});
test('changes divider resizes, keeps drafts and selection, remembers width and adapts to mobile',async({page})=>{
  await login(page);
  const panel=page.locator('#changes-panel'),divider=page.getByRole('separator',{name:'Tilpas filpanelets bredde'});
  await page.locator('#message').fill('Keep this draft');await page.locator('.changed-file').first().click();
  const selected=await page.locator('#change-detail h3').first().textContent();
  const initial=await panel.boundingBox(),handle=await divider.boundingBox();
  await page.mouse.move(handle.x+handle.width/2,handle.y+70);await page.mouse.down();await page.mouse.move(handle.x-220,handle.y+70,{steps:8});await page.mouse.up();
  expect((await panel.boundingBox()).width).toBeGreaterThan(initial.width+200);
  await expect(page.locator('#message')).toHaveValue('Keep this draft');await expect(page.locator('#change-detail h3').first()).toHaveText(selected);
  const resized=(await panel.boundingBox()).width;
  await divider.focus();await divider.press('ArrowLeft');expect((await panel.boundingBox()).width).toBe(resized+20);
  await divider.press('End');expect((await page.locator('.conversation').boundingBox()).width).toBeGreaterThanOrEqual(359);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('#message').fill('long');await page.locator('#send').click();await expect(page.locator('#interrupt')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#interrupt').click();
  await divider.press('Home');expect((await panel.boundingBox()).width).toBe(280);
  await divider.dblclick();expect((await panel.boundingBox()).width).toBe(350);
  await divider.press('ArrowLeft');const remembered=(await panel.boundingBox()).width;
  await page.locator('#close-changes').click();await expect(divider).toBeHidden();await page.locator('#toggle-changes').click();expect((await panel.boundingBox()).width).toBe(remembered);
  await page.reload();await expect(divider).toBeVisible();expect((await panel.boundingBox()).width).toBe(remembered);
  await page.setViewportSize({width:390,height:844});await expect(divider).toBeHidden();expect((await panel.boundingBox()).width).toBeLessThanOrEqual(390);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:1440,height:1000});await expect(divider).toBeVisible();expect((await panel.boundingBox()).width).toBe(remembered);
  const cancelHandle=await divider.boundingBox();await page.mouse.move(cancelHandle.x+4,cancelHandle.y+70);await page.mouse.down();await page.mouse.move(cancelHandle.x-120,cancelHandle.y+70);await page.keyboard.press('Escape');await page.mouse.up();expect((await panel.boundingBox()).width).toBe(remembered);await expect(page.locator('body')).not.toHaveClass(/resizing-changes/);
});
