import { test, expect } from '@playwright/test';

async function login(page){
  await page.goto('/');await page.getByLabel('Adgangsnøgle',{exact:true}).fill('browser-test-access-key-123456789');
  await page.getByRole('button',{name:'Forbind til Codex'}).click();
  await expect(page.locator('#connection-label')).toHaveText('Forbundet');
  await page.getByRole('button',{name:/Byg et browser-UI/}).click();
  await expect(page.locator('#session-status')).toHaveText('Klar');
}
test('desktop: history, safe rendering, streaming, approvals, questions, steering, stop, reload and logout',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await login(page);
  await expect(page.locator('#messages')).toContainText('lokale Codex-server');
  expect(await page.evaluate(()=>window.compromised)).toBeUndefined();
  await expect(page.locator('#messages a[href^="javascript:"]')).toHaveCount(0);
  await page.getByText('pwd',{exact:false}).first().click();
  await expect(page.locator('details[open]')).toHaveCount(1);
  await page.locator('#message').fill('test streaming');await page.getByRole('button',{name:'Send besked',exact:true}).click();
  await expect(page.locator('#messages')).toContainText('Svaret streames fra din maskine.');
  await expect(page.locator('#session-status')).toHaveText('Klar');
  await page.locator('#message').fill('approval');await page.getByRole('button',{name:'Send besked',exact:true}).click();
  await expect(page.getByText('Din godkendelse er nødvendig')).toBeVisible();
  await page.getByRole('button',{name:'Godkend én gang'}).click();
  await expect(page.locator('#requests')).toBeEmpty();
  await page.locator('#message').fill('question');await page.getByRole('button',{name:'Send besked',exact:true}).click();
  await page.getByLabel('Hvilken farve?',{exact:true}).fill('Grøn');await page.getByRole('button',{name:'Send svar',exact:true}).click();
  await expect(page.locator('#requests')).toBeEmpty();
  await page.locator('#message').fill('long');await page.getByRole('button',{name:'Send besked',exact:true}).click();
  await expect(page.locator('#interrupt')).toBeVisible();
  await page.locator('#message').fill('Fokusér på tests');await page.locator('#steer').click();
  await expect(page.locator('#messages')).toContainText('Fokusér på tests');
  await page.locator('#interrupt').click();await expect(page.locator('#messages')).toContainText('Stoppet');
  await page.locator('#message').fill('Min kladde');await page.getByRole('button',{name:/Mit andet projekt/}).click();
  await expect(page.locator('#message')).toHaveValue('');await page.getByRole('button',{name:/Byg et browser-UI/}).click();
  await expect(page.locator('#message')).toHaveValue('Min kladde');
  await page.reload();await expect(page.locator('#session-title')).toHaveText('Byg et browser-UI');
  await expect(page.locator('#messages')).toContainText('Fokusér på tests');
  await page.screenshot({path:'test-results/desktop.png',fullPage:true,animations:'disabled'});
  expect(errors).toEqual([]);
  await page.getByRole('button',{name:'Log ud',exact:true}).click();await expect(page.locator('#login')).toBeVisible();
});
test('mobile: navigation, no overflow, search and new project session',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');await page.getByLabel('Adgangsnøgle',{exact:true}).fill('browser-test-access-key-123456789');await page.getByRole('button',{name:'Forbind til Codex'}).click();
  await expect(page.locator('#connection-label')).toHaveText('Forbundet');
  await page.getByRole('button',{name:'Vis sessions',exact:true}).click();
  await page.getByLabel('Søg i sessions').fill('browser');
  await expect(page.locator('.session-row')).toHaveCount(1);
  await page.getByRole('button',{name:/Byg et browser-UI/}).click();
  await expect(page.locator('#sidebar')).not.toHaveClass(/open/);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/mobile.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Vis sessions',exact:true}).click();await page.getByRole('button',{name:'Ny session',exact:false}).click();
  await page.getByLabel('Projektmappe',{exact:true}).fill('/home/demo/new-project');await page.getByRole('button',{name:'Opret session'}).click();
  await expect(page.locator('#session-path')).toHaveText('/home/demo/new-project');
});
test('preferences, translated drafts, changes tabs and queue edit/cancel/steer/recall',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await login(page);
  await page.locator('#message').fill('long');await page.locator('#send').click();await expect(page.locator('#interrupt')).toBeVisible();
  await page.locator('#message').fill('Queue original');await page.locator('#send').click();
  await expect(page.locator('#queue-list')).toContainText('Queue original');
  await page.reload();await expect(page.locator('#queue-list')).toContainText('Queue original');
  await page.locator('#message').press('ArrowUp');await expect(page.locator('#message')).toHaveValue('Queue original');
  await expect(page.locator('#edit-mode')).toContainText('Redigerer');await expect(page.locator('#queue-list')).toBeEmpty();
  await page.locator('#message').fill('Queue edited');await page.locator('#send').click();
  await expect(page.locator('#queue-list')).toContainText('Queue edited');
  await page.getByRole('button',{name:'Send som steer',exact:true}).click();
  await expect(page.locator('#messages')).toContainText('Queue edited');await expect(page.locator('#queue-list')).toBeEmpty();
  await page.locator('#message').press('ArrowUp');await expect(page.locator('#message')).toHaveValue('Queue edited');await expect(page.locator('#edit-mode')).toContainText('Tidligere besked');
  await page.locator('#message').fill('cancel me');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('cancel me');
  await page.getByRole('button',{name:'Annullér besked',exact:true}).click();await expect(page.locator('#queue-list')).toBeEmpty();
  await page.locator('#interrupt').click();await expect(page.locator('#session-status')).toHaveText('Klar');
  await page.locator('#message').fill('Min urørte kladde');
  await page.locator('#workspace [data-language-select]').selectOption('en');
  await expect(page.locator('#message')).toHaveValue('Min urørte kladde');await expect(page.locator('#connection-label')).toHaveText('Connected');await expect(page.locator('#toggle-changes')).toHaveText('Changed files');
  await page.locator('#workspace [data-theme-toggle]').click();
  const theme=await page.locator('html').getAttribute('data-theme');
  await page.locator('#codex-tab').click();await expect(page.locator('#changed-files')).toContainText('app.js');
  await page.locator('.changed-file').click();await expect(page.locator('#change-detail')).toContainText('<script>unsafe</script>');
  await page.screenshot({path:`test-results/changes-${theme}.png`,fullPage:true});
  await page.locator('#git-tab').press('Home');await expect(page.locator('#codex-tab')).toBeFocused();
  await page.locator('#git-tab').click();await expect(page.locator('#changed-files')).toContainText('untracked.txt');await page.locator('.changed-file').click();await expect(page.locator('#change-detail')).toContainText('<script>only text</script>');
  await page.locator('#workspace [data-theme-toggle]').click();await page.screenshot({path:'test-results/changes-other-theme.png',fullPage:true});
  const savedTheme=await page.locator('html').getAttribute('data-theme');
  await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('html')).toHaveAttribute('data-theme',savedTheme);
  await expect(page.locator('#connection-label')).toHaveText('Connected');
  expect(await page.locator('#connection .status-dot').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(savedTheme==='light'?'rgb(22, 132, 71)':'rgb(54, 207, 125)');
  await page.locator('#message').fill('question');await page.locator('#send').click();await page.getByLabel('Hvilken farve?',{exact:true}).fill('Blå');await page.locator('#workspace [data-language-select]').selectOption('da');await expect(page.getByLabel('Hvilken farve?',{exact:true})).toHaveValue('Blå');await page.getByRole('button',{name:'Send svar',exact:true}).click();
  expect(errors).toEqual([]);
});
test('system theme and preferences work without browser storage; mobile panel closes with Escape',async({page})=>{
  await page.emulateMedia({colorScheme:'dark'});
  await page.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked');}});});
  await page.setViewportSize({width:320,height:800});
  await page.goto('/');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await page.locator('#login [data-language-select]').selectOption('en');await page.locator('#login [data-theme-toggle]').click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await page.getByLabel('Access key',{exact:true}).fill('wrong');await page.getByRole('button',{name:'Connect to Codex'}).click();await expect(page.locator('#login-error')).not.toBeEmpty();
  const englishError=await page.locator('#login-error').textContent();await page.locator('#login [data-language-select]').selectOption('da');await expect(page.locator('#login-error')).not.toHaveText(englishError);
  await page.getByLabel('Adgangsnøgle',{exact:true}).fill('browser-test-access-key-123456789');await page.getByRole('button',{name:'Forbind til Codex'}).click();
  await page.locator('#toggle-sidebar').click();await page.getByRole('button',{name:/Byg et browser-UI/}).click();await expect(page.locator('#session-status')).toHaveText('Klar');await page.locator('#toggle-changes').click();await expect(page.locator('#changes-panel')).toBeVisible();await page.locator('#close-changes').press('Escape');await expect(page.locator('#changes-panel')).toBeHidden();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/mobile-light.png',fullPage:true});
});
test('queue consumption races do not resend; failed steer preserves text and disconnect turns red',async({page})=>{
  await login(page);
  await page.locator('#message').fill('approval');await page.locator('#send').click();await expect(page.locator('#requests')).not.toBeEmpty();
  await page.locator('#message').fill('automatic next turn');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('automatic next turn');
  await page.getByRole('button',{name:'Godkend én gang'}).click();await expect(page.locator('#messages')).toContainText('automatic next turn');await expect(page.locator('#queue-list')).toBeEmpty();await expect(page.locator('#session-status')).toHaveText('Klar');
  await page.locator('#message').fill('long');await page.locator('#send').click();await expect(page.locator('#interrupt')).toBeVisible();
  await page.locator('#message').fill('already consumed');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('already consumed');
  let sends=0;page.on('request',req=>{if(req.url().endsWith('/message'))sends++;});
  await page.route('**/queue/*/delete',async route=>{await route.fetch();await route.fulfill({json:{deleted:false}});});
  await page.getByRole('button',{name:'Send som steer',exact:true}).click();await expect(page.locator('#queue-list')).toBeEmpty();expect(sends).toBe(0);await page.unroute('**/queue/*/delete');
  await page.locator('#message').fill('preserve after failure');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('preserve after failure');
  await page.route('**/message',route=>route.fulfill({status:503,json:{error:'Test delivery failure'}}));
  await page.getByRole('button',{name:'Send som steer',exact:true}).click();await expect(page.locator('#queue-list')).toContainText('Afsendelsen blev ikke bekræftet');await expect(page.locator('#queue-list')).toContainText('preserve after failure');
  await page.getByRole('button',{name:'Tag ud af kø og redigér',exact:true}).click();await expect(page.locator('#message')).toHaveValue('preserve after failure');await page.unroute('**/message');
  await page.locator('#message').fill('lost delete acknowledgement');await page.locator('#send').click();await expect(page.locator('#queue-list')).toContainText('lost delete acknowledgement');
  await page.route('**/queue/*/delete',async route=>{await route.fetch();await route.abort('failed');});
  await page.getByRole('button',{name:'Tag ud af kø og redigér',exact:true}).click();await expect(page.locator('#queue-list')).toContainText('Afsendelsen blev ikke bekræftet');await page.unroute('**/queue/*/delete');
  await page.getByRole('button',{name:'Tag ud af kø og redigér',exact:true}).click();await expect(page.locator('#message')).toHaveValue('lost delete acknowledgement');
  await page.locator('#interrupt').click();
  await page.route('**/api/events',route=>route.fulfill({contentType:'text/event-stream',body:'event: status\ndata: {"state":"disconnected"}\n\n'}));await page.reload();await expect(page.locator('#connection-label')).toHaveText('Forbindelse afbrudt');
  const theme=await page.locator('html').getAttribute('data-theme');expect(await page.locator('#connection .status-dot').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(theme==='light'?'rgb(205, 52, 52)':'rgb(242, 105, 105)');
});
