#!/usr/bin/env node
import { access, lstat, mkdir, open, readFile, rename, unlink } from 'node:fs/promises';
import { constants } from 'node:fs';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { homedir, userInfo } from 'node:os';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';

const execute = promisify(execFile);
const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const serviceName = 'remote-codex.service';
const help = `Usage: npm run setup -- [options]

Install and enable a systemd USER service for this checkout. Does not start or
restart it unless requested. Run as the account that owns your Codex sessions.

  --node PATH       Node executable (default: first node found in PATH)
  --dry-run         Validate and print the unit; write nothing, no systemd calls
  --replace         Replace a different existing unit, keeping a private backup
  --start           Start after installation (an active service is not restarted)
  --restart         Restart after installation; disconnects browsers
  --enable-linger   Enable this user's services at boot and after logout
  --help            Show this help

Requires Linux, systemd, npm dependencies already installed, and a maintained
Node LTS runtime (22+). Installs no runtimes or packages and never changes Codex.
`;

export function parseOptions(args) {
  const options = {};
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--node' || arg.startsWith('--node=')) {
      if (options.node !== undefined) throw new Error('--node may only be specified once.');
      options.node = arg === '--node' ? args[++i] : arg.slice(7);
      if (!options.node || options.node.startsWith('--')) throw new Error('--node requires an executable path.');
    } else if (['--dry-run', '--replace', '--start', '--restart', '--enable-linger', '--help'].includes(arg)) options[arg.slice(2)] = true;
    else throw new Error(`Unknown option: ${arg}. Use --help.`);
  }
  if (options.start && options.restart) throw new Error('Choose --start or --restart, not both.');
  return options;
}

function safePath(value) {
  if (!isAbsolute(value) || /[\x00-\x1f\x7f]/.test(value)) throw new Error('Paths must be absolute and contain no control characters.');
  return value;
}
function quote(value) { return '"' + safePath(value).replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('%', '%%') + '"'; }
function literalPath(value) {
  // WorkingDirectory/EnvironmentFile are literal values, not shell words.
  // EnvironmentFile also expands globs; reject ambiguous checkout paths.
  if (/[\\*?\[\]]/.test(value) || /\s$/.test(value)) throw new Error('Project paths cannot contain backslashes, glob characters, or trailing whitespace.');
  return safePath(value).replaceAll('%', '%%');
}
export function renderUnit(template, root, node) {
  if (/["'\\]/.test(node)) throw new Error('The Node executable path cannot contain quotes or backslashes; systemd rejects these executable names.');
  // ':' disables environment-variable expansion in ExecStart, including literal
  // dollar signs in paths. Percent specifiers still need escaping everywhere.
  const replacements = [
    ['# Replace /path/to/remote-codex with the absolute path to your checkout.', '# Generated by scripts/setup-service.mjs. Runtime settings: .remote-codex/service.env'],
    ['WorkingDirectory=/path/to/remote-codex', `WorkingDirectory=${literalPath(root)}`],
    ['ExecStart=/usr/bin/node server/index.js', `ExecStart=:${quote(node)} ${quote(join(root, 'server/index.js'))}`],
    ['EnvironmentFile=-/path/to/remote-codex/.remote-codex/service.env', `EnvironmentFile=-${literalPath(join(root, '.remote-codex/service.env'))}`],
  ];
  for (const [from, to] of replacements) {
    if (template.split(from).length !== 2) throw new Error('The service template has changed; update setup before installing.');
    template = template.replace(from, () => to);
  }
  return template;
}

// Offline lifecycle checks from https://github.com/nodejs/Release/blob/main/schedule.json.
// A supported release line alone is not proof that a particular patch is current.
const supportEnds = { 22: '2027-04-30', 24: '2028-04-30', 26: '2029-04-30' };
export function validateRuntime(info, now = new Date()) {
  const major = Number(info.version?.split('.')[0]);
  if (!/^\d+\.\d+\.\d+$/.test(info.version || '') || major < 22 || !info.lts || !supportEnds[major] || now >= new Date(supportEnds[major] + 'T00:00:00Z')) {
    throw new Error(`Node ${info.version || '(unknown)'} is not an accepted maintained LTS runtime. Install an updated Node 22/24 LTS release and select it with --node /absolute/path/to/node. Future LTS lines require an updated setup utility.`);
  }
}
async function findNode(option, env) {
  if (option) {
    const path = safePath(resolve(option));
    await access(path, constants.X_OK); return path;
  }
  for (const dir of (env.PATH || '').split(':')) {
    if (!dir) continue;
    const path = resolve(dir, 'node');
    try { await access(path, constants.X_OK); if ((await lstat(path)).isDirectory()) continue; return safePath(path); } catch {}
  }
  throw new Error('Node was not found in PATH. Use --node /absolute/path/to/node.');
}
async function existingUnit(path) {
  let file;
  try { file = await open(path, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK); }
  catch (error) { if (error.code === 'ENOENT') return null; throw new Error(`Cannot safely read service file: ${error.message}`); }
  try {
    const info = await file.stat();
    if (!info.isFile() || info.nlink !== 1 || info.uid !== process.getuid() || info.size > 1024 * 1024) throw new Error('Existing service must be a regular file owned by this user, without links.');
    return await file.readFile('utf8');
  } finally { await file.close(); }
}
async function writeExclusive(path, content) {
  const file = await open(path, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW, 0o600);
  try { await file.writeFile(content); await file.sync(); } finally { await file.close(); }
}

export async function setup(args, { env = process.env, root = projectRoot, run = execute, log = console.log, platform = process.platform, now = new Date() } = {}) {
  const options = parseOptions(args);
  if (options.help) { log(help); return; }
  if (platform !== 'linux') throw new Error('This setup utility requires Linux and a systemd user manager.');
  root = safePath(resolve(root));
  const config = env.XDG_CONFIG_HOME || join(homedir(), '.config');
  safePath(config);
  const directory = join(config, 'systemd/user'), target = join(directory, serviceName);
  const node = await findNode(options.node, env);
  // The installed unit does not inherit shell-only Node settings. Probe the same
  // runtime without NODE_OPTIONS/NODE_PATH, and never launch a shell.
  const probeEnv = { ...env }; delete probeEnv.NODE_OPTIONS; delete probeEnv.NODE_PATH;
  const probe = async args => run(node, args, { cwd: root, env: probeEnv, timeout: 15000, maxBuffer: 65536 });
  let info;
  try { info = JSON.parse((await probe(['-p', 'JSON.stringify({version:process.versions.node,lts:process.release.lts||false})'])).stdout); }
  catch { throw new Error(`Cannot run the selected Node executable: ${node}`); }
  log(`Node: ${node} (${info.version})`);
  validateRuntime(info, now);
  await access(join(root, 'server/index.js'), constants.R_OK);
  try { await probe(['--input-type=module', '-e', "await import('ws')"]); }
  catch { throw new Error('Runtime dependencies could not be loaded with the selected Node. Run npm ci in this checkout using that Node, then retry.'); }
  const unit = renderUnit(await readFile(join(root, 'deploy', serviceName), 'utf8'), root, node);
  const before = await existingUnit(target);
  log(`Project: ${root}\nService: ${target}\n\n${unit}`);
  if (options['dry-run']) {
    if (before !== null && before !== unit) log('The existing unit differs; installation will require --replace and keep a backup.');
    log('Dry run: no files written or service commands executed.'); return { node, target, unit };
  }
  if (before !== null && before !== unit && !options.replace) throw new Error('A different service file already exists. Review --dry-run, then use --replace to update it with a backup.');

  const command = async (file, args) => {
    try { return await run(file, args, { env, timeout: 30000, maxBuffer: 65536 }); }
    catch { throw new Error(`${file} ${args.join(' ')} failed. Earlier completed steps were kept; inspect the service and your systemd user manager before retrying. No automatic recovery was attempted.`); }
  };
  const systemctl = args => command('systemctl', ['--user', ...args]);
  await systemctl(['show', '--property=Version', '--value']);
  await mkdir(directory, { recursive: true, mode: 0o700 });
  const infoDir = await lstat(directory);
  if (!infoDir.isDirectory() || infoDir.uid !== process.getuid() || infoDir.mode & 0o022) throw new Error('The systemd user directory must belong to this user and not be group/world writable or a symlink.');
  if (before !== unit) {
    const suffix = `${Date.now()}-${randomBytes(4).toString('hex')}`, temporary = join(directory, `.${serviceName}.${suffix}.tmp`);
    if (await existingUnit(target) !== before) throw new Error('Service file changed during setup; retry after reviewing it.');
    if (before !== null) {
      const backup = `${target}.backup-${suffix}`;
      await writeExclusive(backup, before); log(`Previous unit backed up to: ${backup}`);
    }
    try { await writeExclusive(temporary, unit); await rename(temporary, target); }
    finally { await unlink(temporary).catch(error => { if (error.code !== 'ENOENT') throw error; }); }
    log('Service file installed.');
  } else log('Service file already matches; no rewrite needed.');
  await systemctl(['daemon-reload']);
  await systemctl(['enable', serviceName]);
  if (options['enable-linger']) await command('loginctl', ['enable-linger', userInfo().username]);
  if (options.restart) {
    log('Restarting the web server as requested; browsers will disconnect and need to log in again.');
    await systemctl(['restart', serviceName]);
  } else if (options.start) await systemctl(['start', serviceName]);
  log(options.restart ? 'Service restarted.' : options.start ? 'Service started (an already active service was left running).' : 'Service enabled. The running process was not started or restarted.');
  log('Status: systemctl --user status remote-codex.service\nLogs: journalctl --user -u remote-codex.service -n 50 --no-pager');
  if (!options['enable-linger']) log('For boot startup and operation after logout, enable lingering if needed: loginctl enable-linger');
  log('Keep this Node installation updated. Setup checks the release line, not whether every security patch is installed.');
  return { node, target, unit };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  setup(process.argv.slice(2)).catch(error => { console.error(`Setup failed: ${error.message}`); process.exitCode = 1; });
}
